### PR TITLE
PR: Add Gtihub username to PR information

### LINKED ISSUE #95: Add user to rendered changelog
Concept:

###############################################################################
### Pull Requests Merged

* [PR 1](https://github.com/pydanny/arepa/pull/1) - Initial Update, by @goanpeca 

In this release 1 pull request was closed.

###############################################################################

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #95

## Example:

```markdown
## Version 0.3 (2017-10-10)

### Issues Closed

* [Issue 74](https://github.com/spyder-ide/loghub/issues/74) - Make 0.3 release
* [Issue 63](https://github.com/spyder-ide/loghub/issues/63) - Add PR link / commit link inside issue ([PR 69](https://github.com/spyder-ide/loghub/pull/69) by [@goanpeca](https://github.com/goanpeca))

In this release 2 issues were closed.

### Pull Requests Merged

* [PR 69](https://github.com/spyder-ide/loghub/pull/69) - PR: Add extra links for related issues and prs by [@goanpeca](https://github.com/goanpeca) ([63](https://github.com/spyder-ide/loghub/issues/63))

In this release 1 pull request was closed.
```

### Issues Closed

* [Issue 74](https://github.com/spyder-ide/loghub/issues/74) - Make 0.3 release
* [Issue 63](https://github.com/spyder-ide/loghub/issues/63) - Add PR link / commit link inside issue ([PR 69](https://github.com/spyder-ide/loghub/pull/69) by [@goanpeca](https://github.com/goanpeca))

In this release 2 issues were closed.

### Pull Requests Merged

* [PR 69](https://github.com/spyder-ide/loghub/pull/69) - PR: Add extra links for related issues and prs by [@goanpeca](https://github.com/goanpeca) ([63](https://github.com/spyder-ide/loghub/issues/63))

In this release 1 pull request was closed.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@djhoese, what do you think about this one? Is it ok for you?

**Comment by djhoese** [comment]
What does it look like on a pull request listed? I'm not sure I'd care for it on the issue section but would like it on the pull request section. Regardless, in the example above if I am the author of the PR I would remove the comma between the PR number and `by @djhoese`.

**Comment by goanpeca** [comment]
The PR would look similar, (not . between brackets but as part of the issue title

*   PR 45   Some title by [@ccordoba12](ccordoba12 )  [#95]

**Comment by ccordoba12** [comment]
> I would remove the comma between the PR number and by `@djhoese`.

I agree with this.

**Comment by goanpeca** [comment]
@djhoese @ccordoba12 look at the description to see how it looks.

**Comment by ccordoba12** [comment]
> PR 69 - PR: Add extra links for related issues and prs by @goanpeca (63)

I think a comma is missing in this case:

PR 69 - PR: Add extra links for related issues and prs**,** by @goanpeca (63)

**Comment by goanpeca** [comment]
Added requested fix @ccordoba12 

Let me know if this is ready to make the release!

**Review by ccordoba12 — APPROVED** [review]
Thanks @goanpeca! This is a really nice improvement!

**Pull request merged**
