### PR TITLE
PR: Add ability to group PRs with issues

### LINKED ISSUE #90: Add ability to group pull requests by labels
My projects tend to have a lot of pull requests for new features and bug fixes that don't get a corresponding issue created. It seems `loghub` only groups issues. I'm willing to add this feature if it is something you are willing to add to the project.

It might be easiest as a single flag to say "include pull requests in groups".

### PR DESCRIPTION
**Pull request by djhoese**
Fixes #90.

This is possibly a WIP. I'm not super proud of how ugly the code got with trying to accomplish this feature. As described in #90 my projects have PRs that have no corresponding issue, but I would like them in label groups. This PR is a first attempt at making this functionality work.

Additionally my preferences differ from the default loghub behavior in that I don't want my changelog to include the related PRs as a list at the end of the mentioned issue. I haven't done anything to the code to limit this functionality, but it may make sense to add it since adding PRs to the groups makes listing them after the issue redundant (although I agree that listing multiple PRs and an issue for one single topic seems like a bad idea). I think adding a flag for this functionality would be good enough or filtering out related issues/PRs from a certain issue/PR's information would be a reasonable behavior.

Does this PR deserve a separate template?

Lastly, is there a reason that `i['url']` isn't used for PRs and issues in the templates?

### CODE REVIEW

**Comment by djhoese** [comment]
The output for this feature ends up looking something like the below example which only has one group (yes I realize our inconsistent PR titling):

```
###############################################################################
## Version <RELEASE_VERSION> (2018/02/19)

### Issues Closed

#### Bugs

* [Issue 179](https://github.com/pytroll/satpy/issues/179) - Cannot read AVHRR in AAPP format
* [PR 187](https://github.com/pytroll/satpy/pull/187) - Fix reader configs having mismatched names between filename and config
* [PR 185](https://github.com/pytroll/satpy/pull/185) - Bugfix nwcsaf_pps reader for file discoverability
* [PR 177](https://github.com/pytroll/satpy/pull/177) - Bugfix viirs loading - picked from (xarray)develop branch
* [PR 163](https://github.com/pytroll/satpy/pull/163) - Bugfix float geotiff


In this release 1 issue and 6 pull requests were closed.
```

**Comment by djhoese** [comment]
Actually, it may make sense to remove the `Issues Closed` part of the template too and only list the groups.

**Comment by ccordoba12** [comment]
@goanpeca, please review this one.

**Comment by goanpeca** [comment]
@davidh-ssec thanks for this PR, but in general I don't think that 

>PRs that have no corresponding issue

Is something that should be encouraged. I think it is a bad practice, so including this "specific" behavior does not seem to promote good practices. On the other hand... it might be useful to other users but see next comment :-p

**Comment by goanpeca** [comment]
This deserves a new template probably where the concept fo treating issues and PRs like the same thing can be more succinctly explained.

Now I would probably favor the idea of having some way of grouping PRs also... so maybe `issue-label-group` should become `label-group` and be applied to both... or have the options for


`issue-label-group`  (only issues)

`pr-label-group`  (only PRs)

`label-group`  (applies to both)

Maybe this is more general and makes it as flexible as needed?

**Comment by djhoese** [comment]
> I think it is a bad practice

There is "best practice" and "what is possible". To me **requiring** an issue for a pull request/feature seems redundant and clutters both inboxes and github notifications. Github treats pull requests and issues very similar, even the loghub github query gets them as one list. I can see how in a "perfect" situation the person creating a bug report or requesting a feature is **not** the person implementing the fix/feature then it makes perfect sense that an issue and a pull request are both made. In any other situation I'm not sure they both *need* to get created. Do you have a link to a popular blog/developer's statement saying that they prefer this? I've been trying to google for it and can't find anyone saying this is best practice. I understand the appeal, I've just never seen someone say it. Regardless, github doesn't require that you make an issue before making a pull request or that both be made so if loghub can support it I think it wouldn't be a bad idea (even if the library is a spyder-ide only package).

> This deserves a new template

Sounds good.

> Now I would probably favor the idea of having some way of grouping PRs also...

I had considered this, but then thought about what the end result would be. I can't think of a reason why someone would want to list issues and pull requests in separate groups. If they really did they could get around this issue by creating separate labels for pull requests and issues. What I was hoping to get as output from loghub was a series of groups showing what things changed in this version (bugs fixed, features added, backwards compatibility changes, documentation updated, etc). To separate PRs and issues at that point seems odd to me, but of course my use case wasn't needed by you guys so far so who am I to say that someone wouldn't want to separate the PR and issue groups.

So anyway, I can try to implement individual label groups (issues only, prs only, both) and you can see how it feels to you. I do have some questions about it though:

1. What does the template get? 3 different series of groups? One series of groups joined? What if a PR only group is the same as an issues only group?
2. If someone specifies certain groups for the only's and a different group for the both, is that an error? Does that mean that there are groups that only PRs (or issues) are wanted and other groups where both are wanted? What do the templates get in this case?

Difficult to predict what everyone would want. Sorry for opening the flood gates.

**Comment by djhoese** [comment]
@goanpeca In response to your comment on the issue:

I'm not sure why you assume that the projects I work on are my own personal projects. I work on multiple projects with many contributors and none of them have a **requirement** that issues be made for every pull request. Projects typically have a separate form of communication where ideas are discussed that may not need to be tracked by an issue tracker like github. When ideas are in the brainstorming phase, or someone brings up a bug in person, or any other situation. You're right there is probably some aspect of not having the time to do it, but it is also due to the idea that it isn't needed so it isn't done. Like I said above, who says this is best practice? I'm fine being completely wrong and knowing that big open source projects do this (numpy, scipy, matplotlib, etc), but I have never heard of it as a requirement before.

I guess I'll have to bring up this issue at a lighting talk at SciPy 2018. ;)

**Comment by goanpeca** [comment]
@davidh-ssec to summarize after this issue and some internal discussions I am open to this change and want to try to keep things open in general and not "hard code" a specific way of doing things (even if I don't agree with some workflows :wink:).

So far we had the concept of Issues, PRs as separate things and Issues and PRs in parenthesis, but this is still taking into account that PRs should have at least one issue attached to it. In the previous scenario we were only grouping issues not PRs, but there might be a case where one might group PRs using different groupings to the ones defined by issues, because `________`.

So instead of "hard coding" an option for group PRs, we can have also groupings for PRs and provide a new template where issues and PRs are treated as the same thing, that is why I proposed

- `issue-label-group` (only issues)
- `pr-label-group` (only PRs)
- `label-group` (applies to both)

Instead of `--group-prs`, maybe we will get someone saying, I dont use issues at all, I want PRs grouped this way (but having the CLI argument be issue-label -group will be misleading in this case). 

So for most users, including you and us, using `label-group` is actually enough but we also have grouping that only apply to PRs and only apply to Issues?

Or maybe what we really need is to use is `label-group` and deprecate `issues-label-group`, and provide the grouping for issues and PRs only, and when someone brings up a use case for grouping using different groupings we can re raise that issue :-p 

Since I think the behavior in general is different I think it deserves a different template, otherwise we need a new CLI argument, and the logic in the template starts to get more complicated, don't you think?

---

**Are there any other workflows you can think of at this moment, so that we maybe take them into account?**

Thoughts?

**Comment by goanpeca** [comment]
Overall @davidh-ssec, sorry I was reluctant on these changes at first. I really value your contribution and that more people seem to use loghub for their work :-), this started as a simple utility for the spyder project and has grown into a bit more now :-)

I would like to encourage you to open more issues with things you think we can improve  and other workflows that we might be not using at the moment.

Thanks a lot!

**Comment by djhoese** [comment]
I think it's possible that any of the combinations is possible:

1. No groups, list issues and PRs
2. Group issues, list PRs (optionally don't show PRs)
3. List issues, group PRs (optionally don't show issues)
4. Group issues and PRs together (one set of groups)
5. Group issues and PRs (two separate set of groups)

I see all of these as semi-likely except for maybe 5. So maybe for the most flexibility I should get rid of `group-prs`, do what you say with the three command line flags for issue groups, pr groups, and label groups. In the code I can put the general label groups in to the individual list of issue and pr groups. I think then the rest of the code can do things based on those two lists. The resulting template render could get three dictionaries (I think) and could do whatever it wants with those dictionaries.

As for choosing which template: I think the current `_groups.txt` template would have to be `_issues_groups.txt` (2 above) and then new ones for `_prs_groups.txt` (3 above) and `_groups.txt` (4 above). I haven't thought too much about this and how these templates would differ, but we can discuss that when it gets that far.

**Comment by goanpeca** [comment]
Sounds great, want to update the PR :-) ?

**Comment by djhoese** [comment]
Yeah I'll try to find time today. So I'll get rid of `--group-prs` and make the three `label-group` flags work.

**Comment by ccordoba12** [comment]
@davidh-ssec, don't forget to add tests for new functionality.

**Comment by djhoese** [comment]
@ccordoba12 Aw man, now you're going to tell me about best practice too? lol Just kidding. Will do.

**Comment by goanpeca** [comment]
>Aw man, now you're going to tell me about best practice too? lol Just kidding. Will do.

XD, it is! but if you check the tests we have, it is pretty easy to make a new one

**Comment by djhoese** [comment]
@goanpeca What are your thoughts on how many templates should be added? lobhug could just include the templates it has plus one more for grouping PRs and issues together (1 changelog + 1 release = 2 additional template overall). Or I can make another additional template for listing issues and grouping PRs.

If we're going crazy I could also make a template for listing the issue groups and PR groups separately, but I'm not sure that needs to exist.

**Comment by goanpeca** [comment]
@ccordoba12 ?

@davidh-ssec the idea is probably to keep the logic as simple as possible per template, cause in reality we could have one uber template that handled everything

**Comment by djhoese** [comment]
If it changes your answer at all, I'm almost done with doing `X_label_groups.txt`, `X_issue_groups.txt`, and `X_pr_groups.txt`.

**Comment by goanpeca** [comment]
Well go for it :-p

**Comment by djhoese** [comment]
Still need to add tests, but thought if you guys wanted to take a look I'd give you a chance. I'd also like to add an option to turn off the "related" issues and PRs. If you want that in another PR let me know.

**Comment by goanpeca** [comment]
> "related" issues and PRs.

Hmm lets open a new issue to track that ?

**Comment by djhoese** [comment]
@goanpeca @ccordoba12 Do either of you have a suggestion for adding tests for grouping PRs since loghub doesn't label its PRs? I can add tests that have results only have issues in the groups (doing this actually brought out another bug in my code).

**Comment by goanpeca** [comment]
Well this PR could be the basis for the test... or you could create a separate PR that changes one line in the README or something to test the tests...

**Comment by djhoese** [comment]
@goanpeca How do you guys feel about mocking things? I could mock the github response to return what I want. It ruins consistency with the other tests, but does open the doors to testing whatever.

**Comment by dopplershift** [comment]
@goanpeca I just wanted to add another data point to the "not all PRs have issues" camp:
1. I can't control what community members contribute
2. I don't bother to open an issue every time I create a PR to fix the CI build--which seems to be a once-per-week occurrence
3. If I notice a quick bug to fix, I don't *add* additional work to create an issue when the PR is really quick

Just wanted to give another viewpoint. I also want to add that I value having loghub exist, so thanks for putting it out there!

**Comment by djhoese** [comment]
@goanpeca I see you guys already use `mock` for the argv tests so it wouldn't even require an additional dependency for tests (could load from unittest when python 2 support is dropped).

**Comment by djhoese** [comment]
My latest commit is an example of what a mocked version of a test looks like. I'd like to add more if this doesn't disgust you. ;)

**Comment by goanpeca** [comment]
>@goanpeca I just wanted to add another data point to the "not all PRs have issues" camp:

Thanks for the pointers @dopplershift 

>I can't control what community members contribute

True!

>I don't bother to open an issue every time I create a PR to fix the CI build--which seems to be a once-per-week occurrence

Yes, indeed!

>If I notice a quick bug to fix, I don't add additional work to create an issue when the PR is really quick

Makes sense

>Just wanted to give another viewpoint. I also want to add that I value having loghub exist, so thanks for putting it out there!

Thanks for the feedback :-)

**Comment by goanpeca** [comment]
@davidh-ssec I am fine with mocks, but eventually having "real" tests does add more confidence to the results.

**Comment by goanpeca** [comment]
@davidh-ssec we also use ISort for sorting imports, that is the circleci failure

```
    -from mock import patch, MagicMock
    +from mock import MagicMock, patch
```

**Comment by djhoese** [comment]
> but eventually having "real" tests does add more confidence to the results.

Yeah it might turn in to splitting things in to unit/functional/integration tests in the future. Adding this functionality and testing really does open the doors where real world tests are going to be more difficult to set up.

**Comment by djhoese** [comment]
@goanpeca @ccordoba12 Unless you want me to change something I've done recently or add more tests I think this is ready for merging.

**Review by goanpeca — APPROVED** [review]
LGTM :-)

**Pull request merged**
