### PR TITLE
PR: Add options to display/hide related issues and related PRs

### LINKED ISSUE #93: Add option to disable related issues and PRs
Sometimes relationships between PRs and issues can get complicated or a user may not want to list the related PRs/issues next to the entry for an issue/PR. I'd like to propose a command line flag to simply turn off this additional information. Essentially turning off the call to `filter_issues_fixed_by_prs(filtered_issues, filtered_prs)` in the `formatter.py` code.

It could alternatively be passed to the template so it could decide not to show the relationships.

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #93

### CODE REVIEW

**Comment by goanpeca** [comment]
@djhoese could you check this?

**Comment by djhoese** [comment]
I did a simple test on the pytroll/satpy repository for our upcoming 0.20 release.

Old:

```
#### Features added

* [PR 1067](https://github.com/pytroll/satpy/pull/1067) - Add GOES-17 support to the 'geocat' reader
* [PR 1065](https://github.com/pytroll/satpy/pull/1065) - Add AHI airmass, ash, dust, fog, and night_microphysics RGBs
* [PR 1061](https://github.com/pytroll/satpy/pull/1061) - Add support for NUCAPS Science EDRs
* [PR 1047](https://github.com/pytroll/satpy/pull/1047) - Remove deprecated abstractproperty usage ([112](https://github.com/pytroll/satpy/issues/112))
* [PR 1020](https://github.com/pytroll/satpy/pull/1020) - Feature Sentinel-3 Level-2 SST
* [PR 988](https://github.com/pytroll/satpy/pull/988) - Remove py27 tests and switch to py38
* [PR 964](https://github.com/pytroll/satpy/pull/964) - Update SEVIRI L2 BUFR reader to handle BUFR products from EUMETSAT Data Centre
* [PR 839](https://github.com/pytroll/satpy/pull/839) - Add support of colorbar 
* [PR 811](https://github.com/pytroll/satpy/pull/811) - Daskify and test avhrr_l1b_aapp  reader ([809](https://github.com/pytroll/satpy/issues/809))
```

With your branch and `--no-links` added to the same command as the above:

```
#### Features added

* [PR 1067](https://github.com/pytroll/satpy/pull/1067) - Add GOES-17 support to the 'geocat' reader
* [PR 1065](https://github.com/pytroll/satpy/pull/1065) - Add AHI airmass, ash, dust, fog, and night_microphysics RGBs
* [PR 1061](https://github.com/pytroll/satpy/pull/1061) - Add support for NUCAPS Science EDRs
* [PR 1047](https://github.com/pytroll/satpy/pull/1047) - Remove deprecated abstractproperty usage
* [PR 1020](https://github.com/pytroll/satpy/pull/1020) - Feature Sentinel-3 Level-2 SST
* [PR 988](https://github.com/pytroll/satpy/pull/988) - Remove py27 tests and switch to py38
* [PR 964](https://github.com/pytroll/satpy/pull/964) - Update SEVIRI L2 BUFR reader to handle BUFR products from EUMETSAT Data Centre
* [PR 839](https://github.com/pytroll/satpy/pull/839) - Add support of colorbar
* [PR 811](https://github.com/pytroll/satpy/pull/811) - Daskify and test avhrr_l1b_aapp  reader
```

Looks good to me. I'm a little worried that `--no-links` could be confusing. It makes me think "don't include links to the GitHub PR or issue rather than "don't worry about PR/issue relationships". That said, I don't have a better name.

**Comment by goanpeca** [comment]
Thanks for checking!

I am open for better name suggestions :-p 

`--hide-relations` `--skip-relations` `--no-relations`?

**Comment by djhoese** [comment]
I feel like "reference" could be used in there. "--no-refs" but that seems a little git-y so maybe not the best.

**Comment by goanpeca** [comment]
@ccordoba12 do you have a suggestion?

**Comment by ccordoba12** [comment]
> "--no-refs" but that seems a little git-y so maybe not the best.

I like this one, but I agree with @djhoese that users could think it's related to git. What about `--no-related-issues`?

**Comment by ccordoba12** [comment]
Also, could you fix codecov so it doesn't flag PRs as failing?

**Comment by goanpeca** [comment]
>I like this one, but I agree with @djhoese that users could think it's related to git. What about --no-related-issues?

Well the thing is we show this for issues (with links to PR) and for PRs( with links to issues) so should that option remove all? or ?


>Also, could you fix codecov so it doesn't flag PRs as failing?

YEs

**Comment by ccordoba12** [comment]
> so should that option remove all?

There could be two options: `--no-related-issues` and `--no-related-prs`. When both are passed, then no related links would be shown.

**Comment by goanpeca** [comment]
>There could be two options: --no-related-issues and --no-related-prs. When both are passed, then no link related links would be shown.

👍

**Review by ccordoba12 — COMMENTED** [review]
Could you add a couple of tests that check this new functionality is working as expected?

**Comment by goanpeca** [comment]
>Could you add a couple of tests that check this new functionality is working as expected?

Yeah, I am looking at that

**Comment by goanpeca** [comment]
Added tests @ccordoba12 !

**Review by ccordoba12 — APPROVED** [review]
Tests looks pretty good! Great addition @goanpeca!!

**Pull request merged**
